/*
 * miniJacobian.c
 *
 * Embedded MATLAB Coder code generation for M-function 'miniJacobian'
 *
 * C source code generated on: Tue Nov 09 18:21:04 2010
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "miniIKSolve.h"
#include "miniJacobian.h"

/* Type Definitions */

/* Named Constants */

/* Variable Declarations */

/* Variable Definitions */

/* Function Declarations */

/* Function Definitions */
void m_miniJacobian(const real_T eml_in1[21], real_T eml_Jsym[378])
{
  real_T eml_HY;
  real_T eml_LAP;
  real_T eml_LAR;
  real_T eml_LEB;
  real_T eml_LHP;
  real_T eml_LHR;
  real_T eml_LHY;
  real_T eml_LKP;
  real_T eml_LSP;
  real_T eml_LSR;
  real_T eml_LSY;
  real_T eml_RAP;
  real_T eml_RAR;
  real_T eml_REB;
  real_T eml_RHP;
  real_T eml_RHR;
  real_T eml_RHY;
  real_T eml_RKP;
  real_T eml_RSP;
  real_T eml_RSR;
  real_T eml_RSY;
  real_T eml_t3883;
  real_T eml_t3884;
  real_T eml_t3887;
  real_T eml_t3889;
  real_T eml_t3890;
  real_T eml_t3891;
  real_T eml_t3892;
  real_T eml_t3893;
  real_T eml_t3895;
  real_T eml_t3899;
  real_T eml_t3900;
  real_T eml_t3902;
  real_T eml_t3904;
  real_T eml_t3905;
  real_T eml_t3906;
  real_T eml_t3907;
  real_T eml_t3910;
  real_T eml_t3911;
  real_T eml_t3916;
  real_T eml_t3917;
  real_T eml_t3918;
  real_T eml_t3921;
  real_T eml_t3923;
  real_T eml_t3925;
  real_T eml_t3926;
  real_T eml_t3927;
  real_T eml_t3934;
  real_T eml_t3935;
  real_T eml_t3940;
  real_T eml_t3941;
  real_T eml_t3942;
  real_T eml_t3943;
  real_T eml_t3944;
  real_T eml_t3945;
  real_T eml_t3947;
  real_T eml_t3948;
  real_T eml_t3949;
  real_T eml_t3951;
  real_T eml_t3952;
  real_T eml_t3953;
  real_T eml_t3965;
  real_T eml_t3955;
  real_T eml_t3958;
  real_T eml_t3959;
  real_T eml_t3960;
  real_T eml_t3961;
  real_T eml_t3962;
  real_T eml_t3963;
  real_T eml_t3964;
  real_T eml_t3970;
  real_T eml_t3971;
  real_T eml_t3972;
  real_T eml_t3973;
  real_T eml_t3975;
  real_T eml_t3976;
  real_T eml_t3980;
  real_T eml_t3981;
  real_T eml_t3983;
  real_T eml_t3985;
  real_T eml_t3986;
  real_T eml_t3987;
  real_T eml_t3988;
  real_T eml_t4030;
  real_T eml_t3990;
  real_T eml_t3994;
  real_T eml_t3995;
  real_T eml_t3996;
  real_T eml_t3997;
  real_T eml_t3998;
  real_T eml_t3999;
  real_T eml_t4000;
  real_T eml_t4003;
  real_T eml_t4005;
  real_T eml_t4010;
  real_T eml_t4011;
  real_T eml_t4018;
  real_T eml_t4014;
  real_T eml_t4015;
  real_T eml_t4016;
  real_T eml_t4017;
  real_T eml_t4021;
  real_T eml_t4022;
  real_T eml_t4024;
  real_T eml_t4025;
  real_T eml_t4026;
  real_T eml_t4027;
  real_T eml_t4028;
  real_T eml_t4029;
  real_T eml_t4034;
  real_T eml_t4035;
  real_T eml_t4036;
  real_T eml_t4037;
  real_T eml_t4045;
  real_T eml_t4046;
  real_T eml_t4047;
  real_T eml_t4048;
  real_T eml_t4051;
  real_T eml_t4052;
  real_T eml_t4053;
  real_T eml_t4054;
  real_T eml_t4055;
  real_T eml_t4056;
  real_T eml_t4057;
  real_T eml_t4058;
  real_T eml_t4059;
  real_T eml_t4062;
  real_T eml_t4064;
  real_T eml_t4065;
  real_T eml_t4066;
  real_T eml_t4067;
  real_T eml_t4068;
  real_T eml_t4069;
  real_T eml_t4070;
  real_T eml_t4071;
  real_T eml_t4082;
  real_T eml_x[378];
  int32_T eml_k;
  /* MINIJACOBIAN */
  /*     JSYM = MINIJACOBIAN(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 5.3. */
  /*     09-Nov-2010 18:19:23 */
  eml_HY = eml_in1[0];
  eml_LAP = eml_in1[5];
  eml_LAR = eml_in1[6];
  eml_LEB = eml_in1[16];
  eml_LHP = eml_in1[3];
  eml_LHR = eml_in1[2];
  eml_LHY = eml_in1[1];
  eml_LKP = eml_in1[4];
  eml_LSP = eml_in1[13];
  eml_LSR = eml_in1[14];
  eml_LSY = eml_in1[15];
  eml_RAP = eml_in1[11];
  eml_RAR = eml_in1[12];
  eml_REB = eml_in1[20];
  eml_RHP = eml_in1[9];
  eml_RHR = eml_in1[8];
  eml_RHY = eml_in1[7];
  eml_RKP = eml_in1[10];
  eml_RSP = eml_in1[17];
  eml_RSR = eml_in1[18];
  eml_RSY = eml_in1[19];
  eml_t3883 = cos(eml_HY);
  eml_t3884 = sin(eml_LHY);
  eml_LHY = cos(eml_LHY);
  eml_t3887 = sin(eml_HY);
  eml_t3889 = eml_t3883 * eml_t3884 + eml_LHY * eml_t3887;
  eml_t3890 = sin(eml_LHP);
  eml_t3891 = cos(eml_LHP);
  eml_t3892 = cos(eml_LKP);
  eml_t3893 = sin(eml_LHR);
  eml_t3895 = eml_t3883 * eml_LHY - eml_t3884 * eml_t3887;
  eml_t3899 = eml_t3890 * eml_t3889 + eml_t3891 * eml_t3893 * eml_t3895;
  eml_t3900 = sin(eml_LKP);
  eml_t3902 = eml_t3891 * eml_t3889 - eml_t3890 * eml_t3893 * eml_t3895;
  eml_t3904 = eml_t3891 * eml_t3889 * 21.0;
  eml_t3905 = eml_t3900 * eml_t3902 * 87.69;
  eml_t3906 = cos(eml_LAR);
  eml_t3907 = cos(eml_LAP);
  eml_t3884 = eml_t3892 * eml_t3899 - eml_t3900 * eml_t3902;
  eml_t3910 = eml_t3907 * eml_t3884;
  eml_t3911 = sin(eml_LAP);
  eml_LHP = eml_t3892 * eml_t3902 + eml_t3899 * eml_t3900;
  eml_LKP = eml_t3911 * eml_LHP;
  eml_t3916 = eml_t3910 + eml_LKP;
  eml_t3917 = cos(eml_LHR);
  eml_t3918 = sin(eml_LAR);
  eml_t3921 = eml_t3890 * eml_t3893 * eml_t3889 + eml_t3891 * eml_t3895;
  eml_t3923 = eml_t3890 * eml_t3895 - eml_t3891 * eml_t3893 * eml_t3889;
  eml_t3925 = eml_t3892 * eml_t3921 * 87.69;
  eml_t3926 = eml_t3900 * eml_t3921 * 21.0;
  eml_t3927 = eml_t3900 * eml_t3923 * 87.69;
  eml_LHY = eml_t3892 * eml_t3921 + eml_t3900 * eml_t3923;
  eml_HY = eml_t3892 * eml_t3923 - eml_t3900 * eml_t3921;
  eml_t3934 = eml_LHY * eml_t3907 - eml_t3911 * eml_HY;
  eml_t3935 = eml_t3906 * eml_t3934 * 34.0;
  eml_t3940 = eml_HY * eml_t3907 + eml_t3911 * eml_LHY;
  eml_t3941 = eml_t3890 * eml_t3895 * 88.0;
  eml_t3942 = eml_t3892 * eml_t3921 * 21.0;
  eml_t3943 = eml_t3892 * eml_t3923 * 87.69;
  eml_t3944 = eml_t3900 * eml_t3923 * 21.0;
  eml_t3945 = eml_t3940 * eml_t3906 * 34.0;
  eml_t3947 = eml_t3892 * eml_t3902 * 87.69;
  eml_t3948 = eml_t3899 * eml_t3900 * 87.69;
  eml_t3949 = eml_t3900 * eml_t3902 * 21.0;
  eml_t3951 = eml_t3911 * eml_t3884 - eml_LHP * eml_t3907;
  eml_t3952 = eml_t3906 * eml_t3951 * 34.0;
  eml_t3953 = eml_t3890 * eml_t3892 * eml_t3917;
  eml_t3965 = eml_t3891 * eml_t3900 * eml_t3917;
  eml_t3884 = eml_t3953 - eml_t3965;
  eml_t3955 = eml_t3907 * eml_t3884;
  eml_t3958 = eml_t3891 * eml_t3892 * eml_t3917 + eml_t3890 * eml_t3900 *
    eml_t3917;
  eml_t3959 = eml_t3911 * eml_t3958;
  eml_t3960 = eml_t3955 + eml_t3959;
  eml_t3961 = eml_t3906 * eml_t3960 * 34.0;
  eml_t3962 = eml_t3891 * eml_t3892 * eml_t3917 * 21.0;
  eml_t3963 = eml_t3890 * eml_t3892 * eml_t3917 * 87.69;
  eml_t3964 = eml_t3890 * eml_t3900 * eml_t3917 * 21.0;
  eml_HY = sin(eml_RHY);
  eml_LHY = cos(eml_RHY);
  eml_t3970 = eml_t3883 * eml_HY + eml_t3887 * eml_LHY;
  eml_t3971 = sin(eml_RHP);
  eml_t3972 = cos(eml_RHP);
  eml_t3973 = sin(eml_RHR);
  eml_t3975 = eml_t3883 * eml_LHY - eml_t3887 * eml_HY;
  eml_t3976 = cos(eml_RKP);
  eml_t3980 = eml_t3970 * eml_t3972 + eml_t3971 * eml_t3973 * eml_t3975;
  eml_t3981 = sin(eml_RKP);
  eml_t3983 = eml_t3970 * eml_t3971 - eml_t3972 * eml_t3973 * eml_t3975;
  eml_t3985 = eml_t3970 * eml_t3972 * 21.0;
  eml_t3986 = cos(eml_RAR);
  eml_t3987 = cos(eml_RAP);
  eml_t3988 = eml_t3980 * eml_t3981;
  eml_t4030 = eml_t3983 * eml_t3976;
  eml_t3990 = sin(eml_RAP);
  eml_LHP = eml_t3980 * eml_t3976 + eml_t3981 * eml_t3983;
  eml_t3994 = eml_t3990 * eml_LHP;
  eml_t3995 = eml_t3994 - eml_t3987 * (eml_t3988 - eml_t4030);
  eml_t3996 = eml_t3980 * eml_t3981 * 87.69;
  eml_t3997 = cos(eml_RHR);
  eml_t3998 = sin(eml_RAR);
  eml_t3999 = eml_t3972 * eml_t3973 * eml_t3975 * 88.0;
  eml_t4000 = eml_t3971 * eml_t3973 * eml_t3975 * 21.0;
  eml_t4003 = eml_t3971 * eml_t3975 + eml_t3970 * eml_t3972 * eml_t3973;
  eml_t4005 = eml_t3972 * eml_t3975 - eml_t3970 * eml_t3971 * eml_t3973;
  eml_LHY = eml_t3976 * eml_t4005 + eml_t3981 * eml_t4003;
  eml_t4010 = eml_t3987 * eml_LHY;
  eml_t4011 = eml_t3981 * eml_t4005;
  eml_t4018 = eml_t3976 * eml_t4003;
  eml_HY = eml_t4011 - eml_t4018;
  eml_t4014 = eml_t3986 * (eml_t4010 + eml_t3990 * eml_HY) * 34.0;
  eml_t4015 = eml_t3976 * eml_t4005 * 87.69;
  eml_t4016 = eml_t3981 * eml_t4003 * 87.69;
  eml_t4017 = eml_t3981 * eml_t4005 * 21.0;
  eml_t4021 = eml_t3990 * eml_LHY - eml_t3987 * eml_HY;
  eml_t4022 = eml_t3971 * eml_t3975 * 88.0;
  eml_t4024 = eml_t3986 * eml_t4021 * 34.0;
  eml_t4025 = eml_t3976 * eml_t4003 * 87.69;
  eml_t4026 = eml_t3976 * eml_t4005 * 21.0;
  eml_t4027 = eml_t3981 * eml_t4003 * 21.0;
  eml_t4028 = eml_t3970 * eml_t3972 * eml_t3973 * 88.0;
  eml_t4029 = eml_t3970 * eml_t3971 * eml_t3973 * 21.0;
  eml_t4034 = eml_t3986 * (eml_LHP * eml_t3987 + eml_t3990 * (eml_t3988 -
    eml_t4030)) * 34.0;
  eml_t4035 = eml_t3980 * eml_t3976 * 87.69;
  eml_t4036 = eml_t3980 * eml_t3981 * 21.0;
  eml_t4037 = eml_t3981 * eml_t3983 * 87.69;
  eml_HY = eml_t3972 * eml_t3981 * eml_t3997 - eml_t3971 * eml_t3976 * eml_t3997;
  eml_LHY = eml_t3972 * eml_t3976 * eml_t3997 + eml_t3971 * eml_t3981 *
    eml_t3997;
  eml_t4045 = eml_t3987 * eml_HY - eml_t3990 * eml_LHY;
  eml_t4046 = eml_t3972 * eml_t3976 * eml_t3997 * 21.0;
  eml_t4047 = eml_t3971 * eml_t3976 * eml_t3997 * 87.69;
  eml_t4048 = eml_t3971 * eml_t3981 * eml_t3997 * 21.0;
  eml_t4051 = eml_t3986 * eml_t4045 * 34.0;
  eml_t4052 = cos(eml_LSP);
  eml_t4053 = cos(eml_LSR);
  eml_t4054 = sin(eml_LSP);
  eml_t4055 = sin(eml_LSR);
  eml_t4056 = cos(eml_LEB);
  eml_t4057 = sin(eml_LEB);
  eml_t4058 = sin(eml_LSY);
  eml_t4059 = cos(eml_LSY);
  eml_t4062 = eml_t4052 * eml_t4059 + eml_t4054 * eml_t4055 * eml_t4058;
  eml_t4064 = eml_t4054 * eml_t4059 - eml_t4052 * eml_t4055 * eml_t4058;
  eml_t4065 = cos(eml_RSP);
  eml_t4066 = cos(eml_RSR);
  eml_t4067 = sin(eml_RSP);
  eml_t4068 = sin(eml_RSR);
  eml_t4069 = cos(eml_REB);
  eml_t4070 = sin(eml_REB);
  eml_t4071 = sin(eml_RSY);
  eml_RSP = cos(eml_RSY);
  eml_RSR = eml_RSP * eml_t4065 + eml_t4071 * eml_t4067 * eml_t4068;
  eml_REB = eml_RSP * eml_t4067 - eml_t4071 * eml_t4065 * eml_t4068;
  eml_RSY = eml_t3890 * eml_t3892 * eml_t3893 - eml_t3891 * eml_t3893 *
    eml_t3900;
  eml_t4082 = eml_t3891 * eml_t3892 * eml_t3893 + eml_t3890 * eml_t3893 *
    eml_t3900;
  eml_RHR = eml_t3911 * eml_t3884;
  eml_RAR = eml_t3907 * eml_t3958;
  eml_LSP = (-eml_RHR) + eml_RAR;
  eml_LSR = eml_t3907 * eml_t4082 - eml_t3911 * eml_RSY;
  eml_LEB = eml_t3890 * eml_t3892 * eml_t3895 * eml_t3917 - eml_t3891 *
    eml_t3895 * eml_t3900 * eml_t3917;
  eml_LSY = eml_t3891 * eml_t3892 * eml_t3895 * eml_t3917 + eml_t3890 *
    eml_t3895 * eml_t3900 * eml_t3917;
  eml_RHP = (-eml_t3910) - eml_LKP;
  eml_RKP = eml_t3972 * eml_t3981 * eml_t3973 - eml_t3971 * eml_t3973 *
    eml_t3976;
  eml_RAP = eml_t3972 * eml_t3973 * eml_t3976 + eml_t3971 * eml_t3981 *
    eml_t3973;
  eml_RHY = eml_t3987 * eml_LHY;
  eml_LKP = eml_t3990 * eml_HY;
  eml_LAP = eml_RHY + eml_LKP;
  eml_LHR = eml_t3987 * eml_RAP + eml_t3990 * eml_RKP;
  eml_LAR = eml_t3998 * eml_t4045;
  eml_HY = eml_t4010 + eml_t3990 * (eml_t4011 - eml_t4018);
  eml_LHP = eml_t3972 * eml_t3981 * eml_t3975 * eml_t3997 - eml_t3971 *
    eml_t3975 * eml_t3976 * eml_t3997;
  eml_t3884 = eml_t3972 * eml_t3975 * eml_t3976 * eml_t3997 + eml_t3971 *
    eml_t3981 * eml_t3975 * eml_t3997;
  eml_LHY = (-eml_t3994) + eml_t3987 * (eml_t3988 - eml_t4030);
  eml_x[0] = (((((((((eml_t3883 * -37.9 + eml_t3904) + eml_t3905) - eml_t3890 *
    eml_t3889 * 88.0) - eml_t3892 * eml_t3899 * 87.69)
    - eml_t3892 * eml_t3902 * 21.0) - eml_t3899 * eml_t3900 * 21.0) - eml_t3906
    * eml_t3916 * 34.0) - eml_t3890 * eml_t3893 *
    eml_t3895 * 21.0) - eml_t3891 * eml_t3893 * eml_t3895 * 88.0) - eml_t3895 *
    eml_t3917 * eml_t3918 * 34.0;
  eml_x[1] = (((((((((eml_t3887 * -37.9 + eml_t3941) + eml_t3942) + eml_t3943) +
    eml_t3944) + eml_t3945) - eml_t3891 * eml_t3895
    * 21.0) - eml_t3900 * eml_t3921 * 87.69) - eml_t3890 * eml_t3893 * eml_t3889
    * 21.0) - eml_t3891 * eml_t3893 * eml_t3889 *
    88.0) - eml_t3889 * eml_t3917 * eml_t3918 * 34.0;
  eml_x[2] = 0.0;
  eml_x[3] = (((((((((eml_t3883 * 37.9 + eml_t3985) + eml_t3996) + eml_t3999) +
    eml_t4000) - eml_t3970 * eml_t3971 * 88.0) -
    eml_t3981 * eml_t3983 * 21.0) - eml_t3980 * eml_t3976 * 21.0) - eml_t3983 *
    eml_t3976 * 87.69) - eml_t3986 * eml_t3995 *
    34.0) - eml_t3975 * eml_t3997 * eml_t3998 * 34.0;
  eml_x[4] = (((((((((eml_t3887 * 37.9 + eml_t4022) + eml_t4024) + eml_t4025) +
    eml_t4026) + eml_t4027) + eml_t4028) + eml_t4029)
    - eml_t3972 * eml_t3975 * 21.0) - eml_t3981 * eml_t4005 * 87.69) - eml_t3970
    * eml_t3997 * eml_t3998 * 34.0;
  eml_x[5] = 0.0;
  eml_x[6] = 0.0;
  eml_x[7] = 0.0;
  eml_x[8] = 0.0;
  eml_x[9] = 0.0;
  eml_x[10] = 0.0;
  eml_x[11] = 0.0;
  eml_x[12] = 0.0;
  eml_x[13] = 0.0;
  eml_x[14] = eml_t3934;
  eml_x[15] = 0.0;
  eml_x[16] = 0.0;
  eml_x[17] = eml_HY;
  eml_x[18] = ((((((((eml_t3904 + eml_t3905) - eml_t3890 * eml_t3889 * 88.0) -
    eml_t3892 * eml_t3899 * 87.69) - eml_t3892 *
    eml_t3902 * 21.0) - eml_t3899 * eml_t3900 * 21.0) - eml_t3906 * eml_t3916 *
    34.0) - eml_t3890 * eml_t3893 * eml_t3895 * 21.0
    ) - eml_t3891 * eml_t3893 * eml_t3895 * 88.0) - eml_t3895 * eml_t3917 *
    eml_t3918 * 34.0;
  eml_x[19] = ((((((((eml_t3941 + eml_t3942) + eml_t3943) + eml_t3944) +
    eml_t3945) - eml_t3891 * eml_t3895 * 21.0) - eml_t3900 *
    eml_t3921 * 87.69) - eml_t3890 * eml_t3893 * eml_t3889 * 21.0) - eml_t3891 *
    eml_t3893 * eml_t3889 * 88.0) - eml_t3889 *
    eml_t3917 * eml_t3918 * 34.0;
  eml_x[20] = 0.0;
  eml_x[21] = 0.0;
  eml_x[22] = 0.0;
  eml_x[23] = 0.0;
  eml_x[24] = 0.0;
  eml_x[25] = 0.0;
  eml_x[26] = 0.0;
  eml_x[27] = 0.0;
  eml_x[28] = 0.0;
  eml_x[29] = 0.0;
  eml_x[30] = 0.0;
  eml_x[31] = 0.0;
  eml_x[32] = eml_t3934;
  eml_x[33] = 0.0;
  eml_x[34] = 0.0;
  eml_x[35] = 0.0;
  eml_x[36] = ((((((eml_t3906 * (eml_t3911 * (eml_t3890 * eml_t3892 * eml_t3889
    * eml_t3917 - eml_t3891 * eml_t3889 * eml_t3900 *
    eml_t3917) - eml_t3907 * (eml_t3891 * eml_t3892 * eml_t3889 * eml_t3917 +
    eml_t3890 * eml_t3889 * eml_t3900 * eml_t3917)) *
    34.0 - eml_t3890 * eml_t3889 * eml_t3917 * 21.0) - eml_t3891 * eml_t3889 *
    eml_t3917 * 88.0) + eml_t3893 * eml_t3889 *
    eml_t3918 * 34.0) + eml_t3890 * eml_t3892 * eml_t3889 * eml_t3917 * 21.0) -
    eml_t3891 * eml_t3892 * eml_t3889 * eml_t3917 *
    87.69) - eml_t3890 * eml_t3889 * eml_t3900 * eml_t3917 * 87.69) - eml_t3891
    * eml_t3889 * eml_t3900 * eml_t3917 * 21.0;
  eml_x[37] = ((((((eml_t3906 * (eml_t3911 * eml_LEB - eml_t3907 * eml_LSY) *
    -34.0 + eml_t3890 * eml_t3895 * eml_t3917 * 21.0) +
    eml_t3891 * eml_t3895 * eml_t3917 * 88.0) - eml_t3893 * eml_t3895 *
    eml_t3918 * 34.0) - eml_t3890 * eml_t3892 * eml_t3895 *
    eml_t3917 * 21.0) + eml_t3891 * eml_t3892 * eml_t3895 * eml_t3917 * 87.69) +
    eml_t3890 * eml_t3895 * eml_t3900 * eml_t3917
    * 87.69) + eml_t3891 * eml_t3895 * eml_t3900 * eml_t3917 * 21.0;
  eml_x[38] = ((((((eml_t3890 * eml_t3893 * 21.0 + eml_t3891 * eml_t3893 * 88.0)
    + eml_t3917 * eml_t3918 * 34.0) + eml_t3906 *
    eml_LSR * 34.0) - eml_t3890 * eml_t3892 * eml_t3893 * 21.0) + eml_t3891 *
    eml_t3892 * eml_t3893 * 87.69) + eml_t3890 *
    eml_t3893 * eml_t3900 * 87.69) + eml_t3891 * eml_t3893 * eml_t3900 * 21.0;
  eml_x[39] = 0.0;
  eml_x[40] = 0.0;
  eml_x[41] = 0.0;
  eml_x[42] = 0.0;
  eml_x[43] = 0.0;
  eml_x[44] = 0.0;
  eml_x[45] = 0.0;
  eml_x[46] = 0.0;
  eml_x[47] = 0.0;
  eml_x[48] = (-eml_t3911) * eml_t4082 - eml_t3907 * eml_RSY;
  eml_x[49] = eml_t3906 * eml_t3917 - eml_t3918 * eml_LSR;
  eml_x[50] = (-eml_t3911) * eml_LSY - eml_t3907 * eml_LEB;
  eml_x[51] = 0.0;
  eml_x[52] = 0.0;
  eml_x[53] = 0.0;
  eml_x[54] = (((((((eml_t3925 + eml_t3926) + eml_t3935) + eml_t3927) +
    eml_t3890 * eml_t3895 * 21.0) + eml_t3891 * eml_t3895 *
    88.0) - eml_t3892 * eml_t3923 * 21.0) + eml_t3890 * eml_t3893 * eml_t3889 *
    88.0) - eml_t3891 * eml_t3893 * eml_t3889 * 21.0;
  eml_x[55] = (((((((eml_t3947 + eml_t3948) + eml_t3949) + eml_t3890 * eml_t3889
    * 21.0) + eml_t3891 * eml_t3889 * 88.0) -
    eml_t3892 * eml_t3899 * 21.0) - eml_t3906 * eml_t3951 * 34.0) - eml_t3890 *
    eml_t3893 * eml_t3895 * 88.0) + eml_t3891 *
    eml_t3893 * eml_t3895 * 21.0;
  eml_x[56] = (((((eml_t3961 + eml_t3962) + eml_t3963) + eml_t3964) + eml_t3890
    * eml_t3917 * 88.0) - eml_t3891 * eml_t3917 * 21.0
    ) - eml_t3891 * eml_t3900 * eml_t3917 * 87.69;
  eml_x[57] = 0.0;
  eml_x[58] = 0.0;
  eml_x[59] = 0.0;
  eml_x[60] = 0.0;
  eml_x[61] = 0.0;
  eml_x[62] = 0.0;
  eml_x[63] = 0.0;
  eml_x[64] = 0.0;
  eml_x[65] = 0.0;
  eml_x[66] = eml_LSP;
  eml_x[67] = (-eml_t3960) * eml_t3918;
  eml_x[68] = eml_RHP;
  eml_x[69] = 0.0;
  eml_x[70] = 0.0;
  eml_x[71] = 0.0;
  eml_x[72] = ((((-eml_t3925) - eml_t3926) - eml_t3935) - eml_t3927) + eml_t3892
    * eml_t3923 * 21.0;
  eml_x[73] = (((eml_t3952 - eml_t3947) - eml_t3948) - eml_t3949) + eml_t3892 *
    eml_t3899 * 21.0;
  eml_x[74] = ((((-eml_t3961) - eml_t3962) - eml_t3963) - eml_t3964) + eml_t3891
    * eml_t3900 * eml_t3917 * 87.69;
  eml_x[75] = 0.0;
  eml_x[76] = 0.0;
  eml_x[77] = 0.0;
  eml_x[78] = 0.0;
  eml_x[79] = 0.0;
  eml_x[80] = 0.0;
  eml_x[81] = 0.0;
  eml_x[82] = 0.0;
  eml_x[83] = 0.0;
  eml_x[84] = (-eml_RAR) + eml_t3911 * (eml_t3953 - eml_t3965);
  eml_x[85] = eml_t3918 * (eml_t3955 + eml_t3959);
  eml_x[86] = eml_t3916;
  eml_x[87] = 0.0;
  eml_x[88] = 0.0;
  eml_x[89] = 0.0;
  eml_x[90] = eml_t3935;
  eml_x[91] = -eml_t3952;
  eml_x[92] = eml_t3906 * (eml_t3955 + eml_t3959) * 34.0;
  eml_x[93] = 0.0;
  eml_x[94] = 0.0;
  eml_x[95] = 0.0;
  eml_x[96] = 0.0;
  eml_x[97] = 0.0;
  eml_x[98] = 0.0;
  eml_x[99] = 0.0;
  eml_x[100] = 0.0;
  eml_x[101] = 0.0;
  eml_x[102] = eml_LSP;
  eml_x[103] = (-eml_t3960) * eml_t3918;
  eml_x[104] = eml_RHP;
  eml_x[105] = 0.0;
  eml_x[106] = 0.0;
  eml_x[107] = 0.0;
  eml_x[108] = eml_t3940 * eml_t3918 * -34.0 - eml_t3889 * eml_t3906 * eml_t3917
    * 34.0;
  eml_x[109] = eml_t3916 * eml_t3918 * -34.0 + eml_t3895 * eml_t3906 * eml_t3917
    * 34.0;
  eml_x[110] = eml_t3893 * eml_t3906 * 34.0 - eml_t3918 * (eml_RHR - eml_t3907 *
    eml_t3958) * 34.0;
  eml_x[111] = 0.0;
  eml_x[112] = 0.0;
  eml_x[113] = 0.0;
  eml_x[114] = 0.0;
  eml_x[115] = 0.0;
  eml_x[116] = 0.0;
  eml_x[117] = 0.0;
  eml_x[118] = 0.0;
  eml_x[119] = 0.0;
  eml_x[120] = 0.0;
  eml_x[121] = (-eml_t3893) * eml_t3918 + eml_t3906 * eml_LSP;
  eml_x[122] = 0.0;
  eml_x[123] = 0.0;
  eml_x[124] = 0.0;
  eml_x[125] = 0.0;
  eml_x[126] = 0.0;
  eml_x[127] = 0.0;
  eml_x[128] = 0.0;
  eml_x[129] = ((((((((eml_t3985 + eml_t3996) + eml_t3999) + eml_t4000) -
    eml_t3970 * eml_t3971 * 88.0) - eml_t3981 * eml_t3983 *
    21.0) - eml_t3980 * eml_t3976 * 21.0) - eml_t3983 * eml_t3976 * 87.69) -
    eml_t3986 * eml_t3995 * 34.0) - eml_t3975 *
    eml_t3997 * eml_t3998 * 34.0;
  eml_x[130] = ((((((((eml_t4022 + eml_t4024) + eml_t4025) + eml_t4026) +
    eml_t4027) + eml_t4028) + eml_t4029) - eml_t3972 *
    eml_t3975 * 21.0) - eml_t3981 * eml_t4005 * 87.69) - eml_t3970 * eml_t3997 *
    eml_t3998 * 34.0;
  eml_x[131] = 0.0;
  eml_x[132] = 0.0;
  eml_x[133] = 0.0;
  eml_x[134] = 0.0;
  eml_x[135] = 0.0;
  eml_x[136] = 0.0;
  eml_x[137] = 0.0;
  eml_x[138] = 0.0;
  eml_x[139] = 0.0;
  eml_x[140] = 0.0;
  eml_x[141] = 0.0;
  eml_x[142] = 0.0;
  eml_x[143] = eml_HY;
  eml_x[144] = 0.0;
  eml_x[145] = 0.0;
  eml_x[146] = 0.0;
  eml_x[147] = ((((((eml_t3986 * (eml_t3990 * (eml_t3970 * eml_t3972 * eml_t3981
    * eml_t3997 - eml_t3970 * eml_t3971 * eml_t3976
    * eml_t3997) + eml_t3987 * (eml_t3970 * eml_t3971 * eml_t3981 * eml_t3997 +
    eml_t3970 * eml_t3972 * eml_t3976 * eml_t3997))
    * 34.0 + eml_t3970 * eml_t3971 * eml_t3997 * 21.0) + eml_t3970 * eml_t3972 *
    eml_t3997 * 88.0) + eml_t3970 * eml_t3973 *
    eml_t3998 * 34.0) + eml_t3970 * eml_t3971 * eml_t3981 * eml_t3997 * 87.69) +
    eml_t3970 * eml_t3972 * eml_t3981 * eml_t3997
    * 21.0) - eml_t3970 * eml_t3971 * eml_t3976 * eml_t3997 * 21.0) + eml_t3970
    * eml_t3972 * eml_t3976 * eml_t3997 * 87.69;
  eml_x[148] = ((((((eml_t3986 * (eml_t3990 * eml_LHP + eml_t3987 * eml_t3884) *
    -34.0 - eml_t3971 * eml_t3975 * eml_t3997 * 21.0)
    - eml_t3972 * eml_t3975 * eml_t3997 * 88.0) - eml_t3973 * eml_t3975 *
    eml_t3998 * 34.0) - eml_t3971 * eml_t3981 * eml_t3975
    * eml_t3997 * 87.69) - eml_t3972 * eml_t3981 * eml_t3975 * eml_t3997 * 21.0)
    + eml_t3971 * eml_t3975 * eml_t3976 *
    eml_t3997 * 21.0) - eml_t3972 * eml_t3975 * eml_t3976 * eml_t3997 * 87.69;
  eml_x[149] = ((((((eml_t3971 * eml_t3973 * 21.0 + eml_t3972 * eml_t3973 *
    88.0) - eml_t3997 * eml_t3998 * 34.0) + eml_t3986 *
    eml_LHR * 34.0) + eml_t3971 * eml_t3981 * eml_t3973 * 87.69) + eml_t3972 *
    eml_t3981 * eml_t3973 * 21.0) - eml_t3971 *
    eml_t3973 * eml_t3976 * 21.0) + eml_t3972 * eml_t3973 * eml_t3976 * 87.69;
  eml_x[150] = 0.0;
  eml_x[151] = 0.0;
  eml_x[152] = 0.0;
  eml_x[153] = 0.0;
  eml_x[154] = 0.0;
  eml_x[155] = 0.0;
  eml_x[156] = 0.0;
  eml_x[157] = 0.0;
  eml_x[158] = 0.0;
  eml_x[159] = (-eml_t3990) * eml_RAP + eml_t3987 * eml_RKP;
  eml_x[160] = (-eml_t3986) * eml_t3997 - eml_t3998 * eml_LHR;
  eml_x[161] = eml_t3990 * eml_t3884 - eml_t3987 * eml_LHP;
  eml_x[162] = 0.0;
  eml_x[163] = 0.0;
  eml_x[164] = 0.0;
  eml_x[165] = (((((((eml_t4014 + eml_t4015) + eml_t4016) + eml_t4017) +
    eml_t3971 * eml_t3975 * 21.0) + eml_t3972 * eml_t3975 *
    88.0) - eml_t3976 * eml_t4003 * 21.0) - eml_t3970 * eml_t3971 * eml_t3973 *
    88.0) + eml_t3970 * eml_t3972 * eml_t3973 * 21.0;
  eml_x[166] = (((((((eml_t4034 + eml_t4035) + eml_t4036) + eml_t4037) +
    eml_t3970 * eml_t3971 * 21.0) + eml_t3970 * eml_t3972 *
    88.0) - eml_t3983 * eml_t3976 * 21.0) + eml_t3971 * eml_t3973 * eml_t3975 *
    88.0) - eml_t3972 * eml_t3973 * eml_t3975 * 21.0;
  eml_x[167] = (((((eml_t4046 + eml_t4047) + eml_t4048) + eml_t3971 * eml_t3997
    * 88.0) - eml_t3972 * eml_t3997 * 21.0) -
    eml_t3986 * eml_t4045 * 34.0) - eml_t3972 * eml_t3981 * eml_t3997 * 87.69;
  eml_x[168] = 0.0;
  eml_x[169] = 0.0;
  eml_x[170] = 0.0;
  eml_x[171] = 0.0;
  eml_x[172] = 0.0;
  eml_x[173] = 0.0;
  eml_x[174] = 0.0;
  eml_x[175] = 0.0;
  eml_x[176] = 0.0;
  eml_x[177] = eml_LAP;
  eml_x[178] = eml_LAR;
  eml_x[179] = eml_LHY;
  eml_x[180] = 0.0;
  eml_x[181] = 0.0;
  eml_x[182] = 0.0;
  eml_x[183] = ((((-eml_t4014) - eml_t4015) - eml_t4016) - eml_t4017) +
    eml_t3976 * eml_t4003 * 21.0;
  eml_x[184] = ((((-eml_t4034) - eml_t4035) - eml_t4036) - eml_t4037) +
    eml_t3983 * eml_t3976 * 21.0;
  eml_x[185] = (((eml_t4051 - eml_t4046) - eml_t4047) - eml_t4048) + eml_t3972 *
    eml_t3981 * eml_t3997 * 87.69;
  eml_x[186] = 0.0;
  eml_x[187] = 0.0;
  eml_x[188] = 0.0;
  eml_x[189] = 0.0;
  eml_x[190] = 0.0;
  eml_x[191] = 0.0;
  eml_x[192] = 0.0;
  eml_x[193] = 0.0;
  eml_x[194] = 0.0;
  eml_x[195] = (-eml_RHY) - eml_LKP;
  eml_x[196] = -eml_LAR;
  eml_x[197] = eml_t3995;
  eml_x[198] = 0.0;
  eml_x[199] = 0.0;
  eml_x[200] = 0.0;
  eml_x[201] = eml_t4014;
  eml_x[202] = eml_t4034;
  eml_x[203] = -eml_t4051;
  eml_x[204] = 0.0;
  eml_x[205] = 0.0;
  eml_x[206] = 0.0;
  eml_x[207] = 0.0;
  eml_x[208] = 0.0;
  eml_x[209] = 0.0;
  eml_x[210] = 0.0;
  eml_x[211] = 0.0;
  eml_x[212] = 0.0;
  eml_x[213] = eml_LAP;
  eml_x[214] = eml_LAR;
  eml_x[215] = eml_LHY;
  eml_x[216] = 0.0;
  eml_x[217] = 0.0;
  eml_x[218] = 0.0;
  eml_x[219] = eml_t3998 * eml_t4021 * -34.0 - eml_t3970 * eml_t3986 * eml_t3997
    * 34.0;
  eml_x[220] = eml_t3995 * eml_t3998 * -34.0 + eml_t3975 * eml_t3986 * eml_t3997
    * 34.0;
  eml_x[221] = eml_t3973 * eml_t3986 * -34.0 + eml_t3998 * eml_LAP * 34.0;
  eml_x[222] = 0.0;
  eml_x[223] = 0.0;
  eml_x[224] = 0.0;
  eml_x[225] = 0.0;
  eml_x[226] = 0.0;
  eml_x[227] = 0.0;
  eml_x[228] = 0.0;
  eml_x[229] = 0.0;
  eml_x[230] = 0.0;
  eml_x[231] = 0.0;
  eml_x[232] = eml_t3973 * eml_t3998 + eml_t3986 * eml_LAP;
  eml_x[233] = 0.0;
  eml_x[234] = 0.0;
  eml_x[235] = 0.0;
  eml_x[236] = 0.0;
  eml_x[237] = 0.0;
  eml_x[238] = 0.0;
  eml_x[239] = 0.0;
  eml_x[240] = (eml_t4052 * eml_t4053 * -109.3 - eml_t4064 * eml_t4057 * 50.0) -
    eml_t4052 * eml_t4053 * eml_t4056 * 50.0;
  eml_x[241] = 0.0;
  eml_x[242] = (eml_t4053 * eml_t4054 * 109.3 - eml_t4062 * eml_t4057 * 50.0) +
    eml_t4053 * eml_t4054 * eml_t4056 * 50.0;
  eml_x[243] = 0.0;
  eml_x[244] = 0.0;
  eml_x[245] = 0.0;
  eml_x[246] = 0.0;
  eml_x[247] = 0.0;
  eml_x[248] = 0.0;
  eml_x[249] = 0.0;
  eml_x[250] = 0.0;
  eml_x[251] = 0.0;
  eml_x[252] = 0.0;
  eml_x[253] = 0.0;
  eml_x[254] = 0.0;
  eml_x[255] = 0.0;
  eml_x[256] = 0.0;
  eml_x[257] = 0.0;
  eml_x[258] = (eml_t4054 * eml_t4055 * 109.3 + eml_t4054 * eml_t4055 *
    eml_t4056 * 50.0) + eml_t4053 * eml_t4054 * eml_t4057 *
    eml_t4058 * 50.0;
  eml_x[259] = (eml_t4053 * 109.3 + eml_t4053 * eml_t4056 * 50.0) - eml_t4055 *
    eml_t4057 * eml_t4058 * 50.0;
  eml_x[260] = (eml_t4052 * eml_t4055 * 109.3 + eml_t4052 * eml_t4055 *
    eml_t4056 * 50.0) + eml_t4052 * eml_t4053 * eml_t4057 *
    eml_t4058 * 50.0;
  eml_x[261] = 0.0;
  eml_x[262] = 0.0;
  eml_x[263] = 0.0;
  eml_x[264] = 0.0;
  eml_x[265] = 0.0;
  eml_x[266] = 0.0;
  eml_x[267] = 0.0;
  eml_x[268] = 0.0;
  eml_x[269] = 0.0;
  eml_x[270] = 0.0;
  eml_x[271] = 0.0;
  eml_x[272] = 0.0;
  eml_x[273] = 0.0;
  eml_x[274] = 0.0;
  eml_x[275] = 0.0;
  eml_x[276] = eml_t4057 * (eml_t4052 * eml_t4058 - eml_t4054 * eml_t4055 *
    eml_t4059) * -50.0;
  eml_x[277] = eml_t4053 * eml_t4057 * eml_t4059 * 50.0;
  eml_x[278] = eml_t4057 * (eml_t4054 * eml_t4058 + eml_t4052 * eml_t4055 *
    eml_t4059) * 50.0;
  eml_x[279] = 0.0;
  eml_x[280] = 0.0;
  eml_x[281] = 0.0;
  eml_x[282] = 0.0;
  eml_x[283] = 0.0;
  eml_x[284] = 0.0;
  eml_x[285] = 0.0;
  eml_x[286] = 0.0;
  eml_x[287] = 0.0;
  eml_x[288] = 0.0;
  eml_x[289] = 0.0;
  eml_x[290] = 0.0;
  eml_x[291] = 0.0;
  eml_x[292] = 0.0;
  eml_x[293] = 0.0;
  eml_x[294] = eml_t4062 * eml_t4056 * 50.0 + eml_t4053 * eml_t4054 * eml_t4057
    * 50.0;
  eml_x[295] = eml_t4055 * eml_t4057 * -50.0 + eml_t4053 * eml_t4056 * eml_t4058
    * 50.0;
  eml_x[296] = eml_t4064 * eml_t4056 * -50.0 + eml_t4052 * eml_t4053 * eml_t4057
    * 50.0;
  eml_x[297] = 0.0;
  eml_x[298] = 0.0;
  eml_x[299] = 0.0;
  eml_x[300] = 0.0;
  eml_x[301] = 0.0;
  eml_x[302] = 0.0;
  eml_x[303] = 0.0;
  eml_x[304] = 0.0;
  eml_x[305] = 0.0;
  eml_x[306] = 0.0;
  eml_x[307] = 0.0;
  eml_x[308] = 0.0;
  eml_x[309] = 0.0;
  eml_x[310] = 0.0;
  eml_x[311] = 0.0;
  eml_x[312] = 0.0;
  eml_x[313] = 0.0;
  eml_x[314] = 0.0;
  eml_x[315] = (eml_t4070 * eml_REB * -50.0 - eml_t4065 * eml_t4066 * 109.3) -
    eml_t4065 * eml_t4066 * eml_t4069 * 50.0;
  eml_x[316] = 0.0;
  eml_x[317] = (eml_t4070 * eml_RSR * -50.0 + eml_t4066 * eml_t4067 * 109.3) +
    eml_t4066 * eml_t4067 * eml_t4069 * 50.0;
  eml_x[318] = 0.0;
  eml_x[319] = 0.0;
  eml_x[320] = 0.0;
  eml_x[321] = 0.0;
  eml_x[322] = 0.0;
  eml_x[323] = 0.0;
  eml_x[324] = 0.0;
  eml_x[325] = 0.0;
  eml_x[326] = 0.0;
  eml_x[327] = 0.0;
  eml_x[328] = 0.0;
  eml_x[329] = 0.0;
  eml_x[330] = 0.0;
  eml_x[331] = 0.0;
  eml_x[332] = 0.0;
  eml_x[333] = (eml_t4067 * eml_t4068 * 109.3 + eml_t4067 * eml_t4068 *
    eml_t4069 * 50.0) + eml_t4070 * eml_t4071 * eml_t4066 *
    eml_t4067 * 50.0;
  eml_x[334] = (eml_t4066 * -109.3 - eml_t4066 * eml_t4069 * 50.0) + eml_t4070 *
    eml_t4071 * eml_t4068 * 50.0;
  eml_x[335] = (eml_t4065 * eml_t4068 * 109.3 + eml_t4065 * eml_t4068 *
    eml_t4069 * 50.0) + eml_t4070 * eml_t4071 * eml_t4065 *
    eml_t4066 * 50.0;
  eml_x[336] = 0.0;
  eml_x[337] = 0.0;
  eml_x[338] = 0.0;
  eml_x[339] = 0.0;
  eml_x[340] = 0.0;
  eml_x[341] = 0.0;
  eml_x[342] = 0.0;
  eml_x[343] = 0.0;
  eml_x[344] = 0.0;
  eml_x[345] = 0.0;
  eml_x[346] = 0.0;
  eml_x[347] = 0.0;
  eml_x[348] = 0.0;
  eml_x[349] = 0.0;
  eml_x[350] = 0.0;
  eml_x[351] = eml_t4070 * (eml_t4071 * eml_t4065 - eml_RSP * eml_t4067 *
    eml_t4068) * -50.0;
  eml_x[352] = eml_t4070 * eml_RSP * eml_t4066 * -50.0;
  eml_x[353] = eml_t4070 * (eml_t4071 * eml_t4067 + eml_RSP * eml_t4065 *
    eml_t4068) * 50.0;
  eml_x[354] = 0.0;
  eml_x[355] = 0.0;
  eml_x[356] = 0.0;
  eml_x[357] = 0.0;
  eml_x[358] = 0.0;
  eml_x[359] = 0.0;
  eml_x[360] = 0.0;
  eml_x[361] = 0.0;
  eml_x[362] = 0.0;
  eml_x[363] = 0.0;
  eml_x[364] = 0.0;
  eml_x[365] = 0.0;
  eml_x[366] = 0.0;
  eml_x[367] = 0.0;
  eml_x[368] = 0.0;
  eml_x[369] = eml_RSR * eml_t4069 * 50.0 + eml_t4070 * eml_t4066 * eml_t4067 *
    50.0;
  eml_x[370] = eml_t4070 * eml_t4068 * 50.0 - eml_t4071 * eml_t4066 * eml_t4069
    * 50.0;
  eml_x[371] = eml_REB * eml_t4069 * -50.0 + eml_t4070 * eml_t4065 * eml_t4066 *
    50.0;
  eml_x[372] = 0.0;
  eml_x[373] = 0.0;
  eml_x[374] = 0.0;
  eml_x[375] = 0.0;
  eml_x[376] = 0.0;
  eml_x[377] = 0.0;
  for(eml_k = 0; eml_k < 378; eml_k++) {
    eml_Jsym[eml_k] = eml_x[eml_k];
  }
}
/* End of Embedded MATLAB Coder code generation (miniJacobian.c) */
