/*
 * miniForwardKinematics.c
 *
 * Embedded MATLAB Coder code generation for M-function 'miniForwardKinematics'
 *
 * C source code generated on: Tue Nov 09 18:21:04 2010
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "miniIKSolve.h"
#include "miniForwardKinematics.h"

/* Type Definitions */

/* Named Constants */

/* Variable Declarations */

/* Variable Definitions */

/* Function Declarations */

/* Function Definitions */
void m_miniForwardKinematics(const real_T eml_in1[21], real_T
 eml_constraintSet4[18])
{
  real_T eml_HY;
  real_T eml_LAP;
  real_T eml_LAR;
  real_T eml_LEB;
  real_T eml_LHP;
  real_T eml_LHR;
  real_T eml_LHY;
  real_T eml_LKP;
  real_T eml_LSP;
  real_T eml_LSR;
  real_T eml_LSY;
  real_T eml_RAP;
  real_T eml_RAR;
  real_T eml_REB;
  real_T eml_RHP;
  real_T eml_RHR;
  real_T eml_RHY;
  real_T eml_RKP;
  real_T eml_RSP;
  real_T eml_RSR;
  real_T eml_RSY;
  real_T eml_t4118;
  real_T eml_t4119;
  real_T eml_t4120;
  real_T eml_t4123;
  real_T eml_t4124;
  real_T eml_t4126;
  real_T eml_t4127;
  real_T eml_t4128;
  real_T eml_t4131;
  real_T eml_t4134;
  real_T eml_t4135;
  real_T eml_t4137;
  real_T eml_t4141;
  real_T eml_t4143;
  real_T eml_t4144;
  real_T eml_t4145;
  real_T eml_t4147;
  real_T eml_t4148;
  real_T eml_t4149;
  real_T eml_t4153;
  real_T eml_t4154;
  real_T eml_t4156;
  real_T eml_t4157;
  real_T eml_t4160;
  real_T eml_t4161;
  real_T eml_t4163;
  real_T eml_t4164;
  real_T eml_t4167;
  real_T eml_t4169;
  real_T eml_t4170;
  real_T eml_t4171;
  real_T eml_t4172;
  real_T eml_t4175;
  real_T eml_t4177;
  real_T eml_t4179;
  real_T eml_t4180;
  real_T eml_t4181;
  real_T eml_t4182;
  real_T eml_t4183;
  real_T eml_t4184;
  real_T eml_t4185;
  real_T eml_t4186;
  real_T eml_t4187;
  /* MINIFORWARDKINEMATICS */
  /*     CONSTRAINTSET4 = MINIFORWARDKINEMATICS(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 5.3. */
  /*     09-Nov-2010 18:19:26 */
  eml_HY = eml_in1[0];
  eml_LAP = eml_in1[5];
  eml_LAR = eml_in1[6];
  eml_LEB = eml_in1[16];
  eml_LHP = eml_in1[3];
  eml_LHR = eml_in1[2];
  eml_LHY = eml_in1[1];
  eml_LKP = eml_in1[4];
  eml_LSP = eml_in1[13];
  eml_LSR = eml_in1[14];
  eml_LSY = eml_in1[15];
  eml_RAP = eml_in1[11];
  eml_RAR = eml_in1[12];
  eml_REB = eml_in1[20];
  eml_RHP = eml_in1[9];
  eml_RHR = eml_in1[8];
  eml_RHY = eml_in1[7];
  eml_RKP = eml_in1[10];
  eml_RSP = eml_in1[17];
  eml_RSR = eml_in1[18];
  eml_RSY = eml_in1[19];
  eml_t4118 = sin(eml_HY);
  eml_t4119 = cos(eml_HY);
  eml_t4120 = cos(eml_LHY);
  eml_HY = sin(eml_LHY);
  eml_t4123 = eml_t4120 * eml_t4119 - eml_HY * eml_t4118;
  eml_t4124 = cos(eml_LHP);
  eml_t4126 = sin(eml_LHP);
  eml_t4127 = cos(eml_LKP);
  eml_t4128 = sin(eml_LHR);
  eml_t4131 = eml_t4120 * eml_t4118 + eml_HY * eml_t4119;
  eml_t4134 = eml_t4123 * eml_t4124 + eml_t4131 * eml_t4126 * eml_t4128;
  eml_t4135 = sin(eml_LKP);
  eml_t4137 = eml_t4123 * eml_t4126 - eml_t4131 * eml_t4124 * eml_t4128;
  eml_t4141 = eml_t4123 * eml_t4124 * eml_t4128 + eml_t4131 * eml_t4126;
  eml_t4143 = eml_t4131 * eml_t4124 - eml_t4123 * eml_t4126 * eml_t4128;
  eml_t4144 = cos(eml_LAR);
  eml_t4145 = cos(eml_LAP);
  eml_t4147 = sin(eml_LAP);
  eml_t4148 = cos(eml_LHR);
  eml_t4149 = sin(eml_LAR);
  eml_LHY = cos(eml_RHY);
  eml_HY = sin(eml_RHY);
  eml_t4153 = eml_LHY * eml_t4119 - eml_HY * eml_t4118;
  eml_t4154 = sin(eml_RHP);
  eml_t4156 = cos(eml_RHP);
  eml_t4157 = sin(eml_RHR);
  eml_t4160 = eml_HY * eml_t4119 + eml_LHY * eml_t4118;
  eml_t4161 = cos(eml_RKP);
  eml_t4163 = eml_t4153 * eml_t4156 - eml_t4160 * eml_t4154 * eml_t4157;
  eml_t4164 = sin(eml_RKP);
  eml_t4167 = eml_t4153 * eml_t4154 + eml_t4160 * eml_t4156 * eml_t4157;
  eml_t4169 = eml_t4119 * 37.9;
  eml_t4170 = cos(eml_RAR);
  eml_t4171 = cos(eml_RAP);
  eml_t4172 = sin(eml_RAP);
  eml_t4175 = eml_t4160 * eml_t4156 + eml_t4153 * eml_t4154 * eml_t4157;
  eml_t4177 = eml_t4160 * eml_t4154 - eml_t4153 * eml_t4156 * eml_t4157;
  eml_t4179 = cos(eml_RHR);
  eml_t4180 = sin(eml_RAR);
  eml_t4181 = sin(eml_LSP);
  eml_t4182 = cos(eml_LSR);
  eml_t4183 = sin(eml_LSR);
  eml_t4184 = cos(eml_LEB);
  eml_t4185 = sin(eml_LEB);
  eml_t4186 = sin(eml_LSY);
  eml_t4187 = cos(eml_LSP);
  eml_LEB = cos(eml_LSY);
  eml_LSP = sin(eml_RSP);
  eml_LSY = cos(eml_RSR);
  eml_RAR = sin(eml_RSR);
  eml_LSR = cos(eml_REB);
  eml_RAP = sin(eml_REB);
  eml_RHR = sin(eml_RSY);
  eml_t4119 = cos(eml_RSY);
  eml_HY = cos(eml_RSP);
  eml_LHY = eml_t4124 * eml_t4135 * eml_t4148 - eml_t4126 * eml_t4127 *
    eml_t4148;
  eml_LHP = eml_t4124 * eml_t4127 * eml_t4148 + eml_t4126 * eml_t4135 *
    eml_t4148;
  eml_t4120 = eml_t4145 * eml_LHP + eml_t4147 * eml_LHY;
  eml_LKP = eml_t4143 * eml_t4127 + eml_t4141 * eml_t4135;
  eml_LAP = eml_t4141 * eml_t4127 - eml_t4143 * eml_t4135;
  eml_LHR = eml_t4161 * eml_t4156 * eml_t4179 + eml_t4154 * eml_t4164 *
    eml_t4179;
  eml_LAR = eml_t4161 * eml_t4154 * eml_t4179 - eml_t4164 * eml_t4156 *
    eml_t4179;
  eml_RHY = eml_t4171 * eml_LHR - eml_t4172 * eml_LAR;
  eml_RHP = eml_t4161 * eml_t4175 + eml_t4164 * eml_t4177;
  eml_RKP = eml_t4161 * eml_t4177 - eml_t4164 * eml_t4175;
  eml_constraintSet4[0] = (((((((((eml_t4118 * -37.9 - eml_t4123 * eml_t4124 *
    21.0) + eml_t4123 * eml_t4126 * 88.0) - eml_t4134
    * eml_t4135 * 87.69) + eml_t4134 * eml_t4127 * 21.0) + eml_t4135 * eml_t4137
    * 21.0) + eml_t4127 * eml_t4137 * 87.69) -
    eml_t4144 * (eml_t4145 * (eml_t4134 * eml_t4135 - eml_t4127 * eml_t4137) -
    eml_t4147 * (eml_t4134 * eml_t4127 + eml_t4135 *
    eml_t4137)) * 34.0) - eml_t4131 * eml_t4124 * eml_t4128 * 88.0) - eml_t4131
    * eml_t4126 * eml_t4128 * 21.0) - eml_t4131 *
    eml_t4148 * eml_t4149 * 34.0;
  eml_constraintSet4[1] = (((((((((eml_t4169 - eml_t4131 * eml_t4124 * 21.0) +
    eml_t4131 * eml_t4126 * 88.0) + eml_t4141 *
    eml_t4135 * 21.0) + eml_t4141 * eml_t4127 * 87.69) - eml_t4143 * eml_t4135 *
    87.69) + eml_t4143 * eml_t4127 * 21.0) +
    eml_t4144 * (eml_t4145 * eml_LAP + eml_t4147 * eml_LKP) * 34.0) + eml_t4123
    * eml_t4124 * eml_t4128 * 88.0) + eml_t4123 *
    eml_t4126 * eml_t4128 * 21.0) + eml_t4123 * eml_t4148 * eml_t4149 * 34.0;
  eml_constraintSet4[2] = (((((((eml_t4124 * eml_t4148 * -88.0 - eml_t4126 *
    eml_t4148 * 21.0) + eml_t4128 * eml_t4149 * 34.0) -
    eml_t4144 * eml_t4120 * 34.0) - eml_t4124 * eml_t4135 * eml_t4148 * 21.0) -
    eml_t4124 * eml_t4127 * eml_t4148 * 87.69) -
    eml_t4126 * eml_t4135 * eml_t4148 * 87.69) + eml_t4126 * eml_t4127 *
    eml_t4148 * 21.0) - 44.7;
  eml_constraintSet4[3] = (((((((((eml_t4118 * 37.9 + eml_t4161 * eml_t4163 *
    21.0) + eml_t4153 * eml_t4154 * 88.0) - eml_t4153 *
    eml_t4156 * 21.0) - eml_t4163 * eml_t4164 * 87.69) + eml_t4161 * eml_t4167 *
    87.69) + eml_t4164 * eml_t4167 * 21.0) -
    eml_t4170 * (eml_t4171 * (eml_t4163 * eml_t4164 - eml_t4161 * eml_t4167) -
    eml_t4172 * (eml_t4161 * eml_t4163 + eml_t4164 *
    eml_t4167)) * 34.0) + eml_t4160 * eml_t4154 * eml_t4157 * 21.0) + eml_t4160
    * eml_t4156 * eml_t4157 * 88.0) - eml_t4160 *
    eml_t4180 * eml_t4179 * 34.0;
  eml_constraintSet4[4] = ((((((((((-eml_t4169) + eml_t4160 * eml_t4154 * 88.0)
    - eml_t4160 * eml_t4156 * 21.0) + eml_t4161 *
    eml_t4175 * 21.0) + eml_t4161 * eml_t4177 * 87.69) - eml_t4164 * eml_t4175 *
    87.69) + eml_t4164 * eml_t4177 * 21.0) +
    eml_t4170 * (eml_t4172 * eml_RHP + eml_t4171 * eml_RKP) * 34.0) - eml_t4153
    * eml_t4154 * eml_t4157 * 21.0) - eml_t4153 *
    eml_t4156 * eml_t4157 * 88.0) + eml_t4153 * eml_t4180 * eml_t4179 * 34.0;
  eml_constraintSet4[5] = (((((((eml_t4180 * eml_t4157 * -34.0 - eml_t4154 *
    eml_t4179 * 21.0) - eml_t4156 * eml_t4179 * 88.0) -
    eml_t4170 * eml_RHY * 34.0) + eml_t4161 * eml_t4154 * eml_t4179 * 21.0) -
    eml_t4161 * eml_t4156 * eml_t4179 * 87.69) -
    eml_t4154 * eml_t4164 * eml_t4179 * 87.69) - eml_t4164 * eml_t4156 *
    eml_t4179 * 21.0) - 44.7;
  eml_constraintSet4[6] = (eml_t4185 * (eml_t4187 * eml_LEB + eml_t4181 *
    eml_t4183 * eml_t4186) * 50.0 - eml_t4181 * eml_t4182 *
    109.3) - eml_t4181 * eml_t4182 * eml_t4184 * 50.0;
  eml_constraintSet4[7] = ((eml_t4183 * 109.3 + eml_t4183 * eml_t4184 * 50.0) +
    eml_t4182 * eml_t4185 * eml_t4186 * 50.0) + 86.5;
  eml_constraintSet4[8] = ((eml_t4185 * (eml_t4181 * eml_LEB - eml_t4183 *
    eml_t4186 * eml_t4187) * -50.0 - eml_t4182 * eml_t4187
    * 109.3) - eml_t4182 * eml_t4184 * eml_t4187 * 50.0) + 1.393E+002;
  eml_constraintSet4[9] = (eml_RAP * (eml_t4119 * eml_HY + eml_RAR * eml_RHR *
    eml_LSP) * 50.0 - eml_LSY * eml_LSP * 109.3) -
    eml_LSY * eml_LSR * eml_LSP * 50.0;
  eml_constraintSet4[10] = ((eml_RAR * -109.3 - eml_RAR * eml_LSR * 50.0) -
    eml_LSY * eml_RAP * eml_RHR * 50.0) - 86.5;
  eml_constraintSet4[11] = ((eml_RAP * (eml_t4119 * eml_LSP - eml_RAR * eml_RHR
    * eml_HY) * -50.0 - eml_LSY * eml_HY * 109.3) -
    eml_LSY * eml_LSR * eml_HY * 50.0) + 1.393E+002;
  eml_constraintSet4[12] = (-eml_t4145) * eml_LHY + eml_t4147 * eml_LHP;
  eml_constraintSet4[13] = eml_t4144 * eml_t4128 + eml_t4149 * eml_t4120;
  eml_constraintSet4[14] = (-eml_t4147) * eml_LAP + eml_t4145 * eml_LKP;
  eml_constraintSet4[15] = eml_t4172 * eml_LHR + eml_t4171 * eml_LAR;
  eml_constraintSet4[16] = (-eml_t4170) * eml_t4157 + eml_t4180 * eml_RHY;
  eml_constraintSet4[17] = eml_t4171 * eml_RHP - eml_t4172 * eml_RKP;
}
/* End of Embedded MATLAB Coder code generation (miniForwardKinematics.c) */
